
############################################################################################
# this is the common set of command for all the plugins
#

MACRO(SETUP_PLUGIN PLUGIN_NAME)
    # here we use the command to generate the library    
	#not sure if needed, but for plugins only Msvc need the d suffix
	IF(MSVC)
		SET(TARGET_NO_DEBUG_POSTFIX)
		FAST_MSVC_DISABLE_RTC()
	ENDIF(MSVC)


	SET(TARGET_LABEL_PREFIX "Plugin")
	SET(TARGET_NO_IMPORT_LIB 1)
	SET(TARGET_NO_MANIFEST 1)
	SET(TARGET_NO_LIBPREFIX 1)
	IF(WIN32)
		SET(TARGET_BIN_DIR ${FAST_WORK_BIN_DIR}/${OSG_PLUGINS})
	ELSE(WIN32)
		SET(TARGET_BIN_DIR ${FAST_WORK_LIB_DIR}/${OSG_PLUGINS})
	ENDIF(WIN32)
	SET(TARGET_INSTALL_RUNTIME_DIR ${OSG_PLUGINS})
	SET(TARGET_INSTALL_LIBRARY_DIR ${OSG_PLUGINS})
    IF(NOT TARGET_INSTALL_INCLUDE_DIR)
        SET(TARGET_INSTALL_INCLUDE_DIR ${PLUGIN_NAME})
    ENDIF(NOT TARGET_INSTALL_INCLUDE_DIR)

	SET(TARGET_VERSION ${OSGWORKS_VERSION})
	SET(TARGET_SOVERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_MAJOR_VERSION ${OSGWORKS_MAJOR_VERSION})
	SET(TARGET_MINOR_VERSION ${OSGWORKS_MINOR_VERSION})
	SET(TARGET_PATCH_VERSION ${OSGWORKS_PATCH_VERSION})
	SET(TARGET_BUILD_VERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_PRODUCT_NAME "OpenSceneGraph")
	SET(TARGET_VERSION_RC_INTERNALNAME "OSG")
	SET(TARGET_PRODUCT_COPYRIGHT "Copyright (C) 2009-2016")

    IF(DYNAMIC_OPENSCENEGRAPH)
		FAST_SHARED_LIBRARY("osgdb_${PLUGIN_NAME}")
    ELSE (DYNAMIC_OPENSCENEGRAPH)
		FAST_STATIC_LIBRARY("osgdb_${PLUGIN_NAME}")
    ENDIF(DYNAMIC_OPENSCENEGRAPH)
	
ENDMACRO(SETUP_PLUGIN)

MACRO(SETUP_SERIALIZER_PLUGIN PLUGIN_NAME)

    # here we use the command to generate the library    
	#not sure if needed, but for plugins only Msvc need the d suffix
	IF(MSVC)
		SET(TARGET_NO_DEBUG_POSTFIX)
		FAST_MSVC_DISABLE_RTC()
	ENDIF(MSVC)	

	SET(TARGET_LABEL_PREFIX "Plugins osg serializer")
	SET(TARGET_NO_IMPORT_LIB 1)
	SET(TARGET_NO_MANIFEST 1)
	SET(TARGET_NO_LIBPREFIX 1)
	IF(WIN32)
		SET(TARGET_BIN_DIR ${FAST_WORK_BIN_DIR}/${OSG_PLUGINS})
	ELSE(WIN32)
		SET(TARGET_BIN_DIR ${FAST_WORK_LIB_DIR}/${OSG_PLUGINS})
	ENDIF(WIN32)
	SET(TARGET_INSTALL_RUNTIME_DIR ${OSG_PLUGINS})
	SET(TARGET_INSTALL_LIBRARY_DIR ${OSG_PLUGINS})
    IF(NOT TARGET_INSTALL_INCLUDE_DIR)
        SET(TARGET_INSTALL_INCLUDE_DIR ${PLUGIN_NAME})
    ENDIF(NOT TARGET_INSTALL_INCLUDE_DIR)

	SET(TARGET_VERSION ${OSGWORKS_VERSION})
	SET(TARGET_SOVERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_MAJOR_VERSION ${OSGWORKS_MAJOR_VERSION})
	SET(TARGET_MINOR_VERSION ${OSGWORKS_MINOR_VERSION})
	SET(TARGET_PATCH_VERSION ${OSGWORKS_PATCH_VERSION})
	SET(TARGET_BUILD_VERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_PRODUCT_NAME "OpenSceneGraph")
	SET(TARGET_VERSION_RC_INTERNALNAME "OSG")
	SET(TARGET_PRODUCT_COPYRIGHT "Copyright (C) 2009-2016")

    IF(DYNAMIC_OPENSCENEGRAPH)
		FAST_SHARED_LIBRARY("osgdb_serializers_${PLUGIN_NAME}")
    ELSE (DYNAMIC_OPENSCENEGRAPH)
		FAST_STATIC_LIBRARY("osgdb_serializers_${PLUGIN_NAME}")
    ENDIF(DYNAMIC_OPENSCENEGRAPH)
ENDMACRO(SETUP_SERIALIZER_PLUGIN)

MACRO(SETUP_DEPRECATED_PLUGIN PLUGIN_NAME)
    # here we use the command to generate the library    
	#not sure if needed, but for plugins only Msvc need the d suffix
	IF(MSVC)
		SET(TARGET_NO_DEBUG_POSTFIX)
		FAST_MSVC_DISABLE_RTC()
	ENDIF(MSVC)	

	SET(TARGET_LABEL_PREFIX "Plugins osg deprecated")
	SET(TARGET_NO_IMPORT_LIB 1)
	SET(TARGET_NO_MANIFEST 1)
	SET(TARGET_NO_LIBPREFIX 1)
	IF(WIN32)
		SET(TARGET_BIN_DIR ${FAST_WORK_BIN_DIR}/${OSG_PLUGINS})
	ELSE(WIN32)
		SET(TARGET_BIN_DIR ${FAST_WORK_LIB_DIR}/${OSG_PLUGINS})
	ENDIF(WIN32)
	SET(TARGET_INSTALL_RUNTIME_DIR ${OSG_PLUGINS})
	SET(TARGET_INSTALL_LIBRARY_DIR ${OSG_PLUGINS})
    IF(NOT TARGET_INSTALL_INCLUDE_DIR)
        SET(TARGET_INSTALL_INCLUDE_DIR ${PLUGIN_NAME})
    ENDIF(NOT TARGET_INSTALL_INCLUDE_DIR)
    
	SET(TARGET_VERSION ${OSGWORKS_VERSION})
	SET(TARGET_SOVERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_MAJOR_VERSION ${OSGWORKS_MAJOR_VERSION})
	SET(TARGET_MINOR_VERSION ${OSGWORKS_MINOR_VERSION})
	SET(TARGET_PATCH_VERSION ${OSGWORKS_PATCH_VERSION})
	SET(TARGET_BUILD_VERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_PRODUCT_NAME "OpenSceneGraph")
	SET(TARGET_VERSION_RC_INTERNALNAME "OSG")
	SET(TARGET_PRODUCT_COPYRIGHT "Copyright (C) 2009-2016")

    IF(DYNAMIC_OPENSCENEGRAPH)
		FAST_SHARED_LIBRARY("osgdb_deprecated_${PLUGIN_NAME}" ${ARGN})
    ELSE (DYNAMIC_OPENSCENEGRAPH)
		FAST_STATIC_LIBRARY("osgdb_deprecated_${PLUGIN_NAME}" ${ARGN})
    ENDIF(DYNAMIC_OPENSCENEGRAPH)
ENDMACRO(SETUP_DEPRECATED_PLUGIN)

MACRO(SETUP_OSG_LIB LIB_NAME)
	IF(WIN32)
		SET(TARGET_OUTPUT_PREFIX "osg${OSGWORKS_SOVERSION}-")
	ENDIF(WIN32)
	FAST_MSVC_DISABLE_RTC()

	SET(TARGET_IMPORTLIB_NAME ${LIB_NAME})
	
	SET(TARGET_INSTALL_INCLUDE_DIR ${LIB_NAME})
	IF(NOT OSG_WITHIN_OSGEARTH)
		SET(TARGET_HEADER_BASE_DIR ${OSGWORKS_SOURCE_DIR}/include/${LIB_NAME})
	ENDIF()
	
	LIST(APPEND TARGET_LIBRARIES_VARS OPENTHREADS_LIBRARY)
    IF (OSG_GLES1_AVAILABLE OR OSG_GLES2_AVAILABLE)
		LIST(APPEND TARGET_LIBRARIES_VARS OPENGL_egl_LIBRARY)
    ELSE()
        LIST(APPEND TARGET_LIBRARIES_VARS OPENGL_gl_LIBRARY)
    ENDIF()

	SET(TARGET_VERSION ${OSGWORKS_VERSION})
	SET(TARGET_SOVERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_MAJOR_VERSION ${OSGWORKS_MAJOR_VERSION})
	SET(TARGET_MINOR_VERSION ${OSGWORKS_MINOR_VERSION})
	SET(TARGET_PATCH_VERSION ${OSGWORKS_PATCH_VERSION})
	SET(TARGET_BUILD_VERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_PRODUCT_NAME "OpenSceneGraph")
	SET(TARGET_VERSION_RC_INTERNALNAME "OSG")
	SET(TARGET_PRODUCT_COPYRIGHT "Copyright (C) 2009-2016")

	FAST_SHARED_LIBRARY(${LIB_NAME} ${ARGN})
ENDMACRO(SETUP_OSG_LIB LIB_NAME)

MACRO(SETUP_OSG_STATIC_LIB LIB_NAME)
    IF(WIN32)
        SET(TARGET_OUTPUT_PREFIX "osg${OSGWORKS_SOVERSION}-")
    ENDIF(WIN32)
	FAST_MSVC_DISABLE_RTC()

    SET(TARGET_IMPORTLIB_NAME ${LIB_NAME})

    SET(TARGET_INSTALL_INCLUDE_DIR ${LIB_NAME})
    IF(NOT OSG_WITHIN_OSGEARTH)
        SET(TARGET_HEADER_BASE_DIR ${OSGWORKS_SOURCE_DIR}/include/${LIB_NAME})
    ENDIF()

    LIST(APPEND TARGET_LIBRARIES_VARS OPENTHREADS_LIBRARY)
    IF (OSG_GLES1_AVAILABLE OR OSG_GLES2_AVAILABLE)
        LIST(APPEND TARGET_LIBRARIES_VARS OPENGL_egl_LIBRARY)
    ELSE()
        LIST(APPEND TARGET_LIBRARIES_VARS OPENGL_gl_LIBRARY)
    ENDIF()

    SET(TARGET_VERSION ${OSGWORKS_VERSION})
    SET(TARGET_SOVERSION ${OSGWORKS_SOVERSION})
    SET(TARGET_MAJOR_VERSION ${OSGWORKS_MAJOR_VERSION})
    SET(TARGET_MINOR_VERSION ${OSGWORKS_MINOR_VERSION})
    SET(TARGET_PATCH_VERSION ${OSGWORKS_PATCH_VERSION})
    SET(TARGET_BUILD_VERSION ${OSGWORKS_SOVERSION})
    SET(TARGET_PRODUCT_NAME "OpenSceneGraph")
    SET(TARGET_VERSION_RC_INTERNALNAME "OSG")
    SET(TARGET_PRODUCT_COPYRIGHT "Copyright (C) 2009-2016")

    FAST_STATIC_LIBRARY(${LIB_NAME} ${ARGN})
ENDMACRO(SETUP_OSG_STATIC_LIB LIB_NAME)

MACRO(SETUP_OPENTHREAD_LIB LIB_NAME)
	IF(WIN32)
		SET(TARGET_OUTPUT_PREFIX "ot${OPENTHREADS_SOVERSION}-")
	ENDIF(WIN32)
	FAST_MSVC_DISABLE_RTC()

	SET(TARGET_IMPORTLIB_NAME ${LIB_NAME})
	SET(TARGET_INSTALL_INCLUDE_DIR ${LIB_NAME})

	SET(TARGET_VERSION ${OPENTHREADS_VERSION})
	SET(TARGET_SOVERSION ${OPENTHREADS_SOVERSION})
	SET(TARGET_NO_AUTO_VERSION_RESOURCE 1)

	FAST_SHARED_LIBRARY(${LIB_NAME} ${ARGN})
ENDMACRO(SETUP_OPENTHREAD_LIB LIB_NAME)

# Takes optional second argument (is_commandline_app?) in ARGV1
MACRO(SETUP_APPLICATION APPLICATION_NAME)

	IF(${ARGC} GREATER 1)
		SET(IS_COMMANDLINE_APP ${ARGV1})
	ELSE(${ARGC} GREATER 1)
		SET(IS_COMMANDLINE_APP 1)
	ENDIF(${ARGC} GREATER 1)
	FAST_MSVC_DISABLE_RTC()

	SET(TARGET_NAME ${APPLICATION_NAME})
	SET(TARGET_VERSION ${OSGWORKS_VERSION})
	SET(TARGET_SOVERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_MAJOR_VERSION ${OSGWORKS_MAJOR_VERSION})
	SET(TARGET_MINOR_VERSION ${OSGWORKS_MINOR_VERSION})
	SET(TARGET_PATCH_VERSION ${OSGWORKS_PATCH_VERSION})
	SET(TARGET_BUILD_VERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_PRODUCT_NAME "OpenSceneGraph")
	SET(TARGET_VERSION_RC_INTERNALNAME "OSG")
	SET(TARGET_PRODUCT_COPYRIGHT "Copyright (C) 2009-2016")
    
	IF(IS_COMMANDLINE_APP)
		FAST_COMMANDLINE_APPLICATION(application_${APPLICATION_NAME} ${ARGN})
	ELSE(IS_COMMANDLINE_APP)
		FAST_GUI_APPLICATION(application_${APPLICATION_NAME} ${ARGN})
	ENDIF(IS_COMMANDLINE_APP)	
ENDMACRO(SETUP_APPLICATION)

MACRO(SETUP_COMMANDLINE_APPLICATION APPLICATION_NAME)

	SET(TARGET_NAME ${APPLICATION_NAME})
	SET(TARGET_VERSION ${OSGWORKS_VERSION})
	SET(TARGET_SOVERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_MAJOR_VERSION ${OSGWORKS_MAJOR_VERSION})
	SET(TARGET_MINOR_VERSION ${OSGWORKS_MINOR_VERSION})
	SET(TARGET_PATCH_VERSION ${OSGWORKS_PATCH_VERSION})
	SET(TARGET_BUILD_VERSION ${OSGWORKS_SOVERSION})
	SET(TARGET_PRODUCT_NAME "OpenSceneGraph")
	SET(TARGET_VERSION_RC_INTERNALNAME "OSG")
	SET(TARGET_PRODUCT_COPYRIGHT "Copyright (C) 2009-2016")
	FAST_MSVC_DISABLE_RTC()

	FAST_COMMANDLINE_APPLICATION(application_${APPLICATION_NAME} ${ARGN})
ENDMACRO(SETUP_COMMANDLINE_APPLICATION)

# Takes optional second argument (is_commandline_app?) in ARGV1
MACRO(SETUP_EXAMPLE EXAMPLE_NAME)
	
	SET(TARGET_NAME ${EXAMPLE_NAME})
	IF(${ARGC} GREATER 1)
		SET(IS_COMMANDLINE_APP ${ARGV1})
	ELSE(${ARGC} GREATER 1)
		SET(IS_COMMANDLINE_APP 1)
	ENDIF(${ARGC} GREATER 1)
	SET(TARGET_NO_AUTO_VERSION_RESOURCE 1)
	FAST_MSVC_DISABLE_RTC()

	IF(IS_COMMANDLINE_APP)
		FAST_COMMANDLINE_APPLICATION(application_${EXAMPLE_NAME} ${ARGN})
	ELSE(IS_COMMANDLINE_APP)
		FAST_GUI_APPLICATION(application_${EXAMPLE_NAME} ${ARGN})
	ENDIF(IS_COMMANDLINE_APP)	
ENDMACRO(SETUP_EXAMPLE)


MACRO(SETUP_COMMANDLINE_EXAMPLE EXAMPLE_NAME)
	SET(TARGET_NAME ${EXAMPLE_NAME})
	FAST_MSVC_DISABLE_RTC()
	FAST_COMMANDLINE_APPLICATION(application_${EXAMPLE_NAME} ${ARGN})
ENDMACRO(SETUP_COMMANDLINE_EXAMPLE)

MACRO(REMOVE_CXX_FLAG flag) 
    STRING(REPLACE "${flag}" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}") 
ENDMACRO() 
